# config.toml
# Supabase CLI がプロジェクト ID と各種ディレクトリを認識するための設定ファイル
# supabaseディレクトリに置いたら何をしても作動しないのでここに設置する

# まずプロジェクト参照IDをトップレベルに
project_ref = "gvhbqlaaqlprgvthcxic"

# functions セクションは配列形式で書きます
# ディレクトリは、ルートから見た相対パス
[[functions]]
directory = "supabase/functions"