import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/component/layouts/Header";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "@/components/ui/toaster";
import { BottomNavbar } from "@/components/component/layouts/BottomNavbar";
import { FloatingActionButtons } from "@/components/component/layouts/FloatingActionButtons";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "SNS with Next.js15",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="ja" className="h-full">
        {/* bodyにflex flex-col h-full を適用 */}
        <body className={`${inter.className} flex flex-col h-full`}>
          <Header />
          <main className="flex-1 overflow-y-auto pb-16 md:pb-0">
            {children}
          </main>
          {/* ★ Toaster の前に BottomNavbar を配置 ★ */}
          <FloatingActionButtons />
          <BottomNavbar />
          <Toaster />
        </body>
      </html>
    </ClerkProvider>
  );
}