// app/layout.tsx
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/component/layouts/Header";
import LeftSidebar from "@/components/component/layouts/LeftSidebar";
import { auth } from "@clerk/nextjs/server";
import { ClerkProvider } from "@clerk/nextjs";
import { getCurrentLoginUserData } from "@/lib/data/userQueries";
import { Toaster } from "@/components/ui/toaster";
import { BottomNavbar } from "@/components/component/layouts/BottomNavbar";
import { FloatingActionButtons } from "@/components/component/layouts/FloatingActionButtons";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Prifile SNS with Next.js15",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { userId: clerkId } = await auth();
  const currentLoginUserData = clerkId
    ? await getCurrentLoginUserData(clerkId)
    : null;

  return (
    <ClerkProvider>
      <html lang='ja' className='h-full'>
        <body
          className={`${inter.className} flex flex-col h-full bg-gray-100 dark:bg-gray-900`}
        >
          <Header />
          <div className='flex-1 grid grid-cols-1 md:grid-cols-[auto_1fr] lg:grid-cols-[auto_1fr_auto] w-full max-w-7xl mx-auto'>
            <aside className='hidden md:block md:w-[240px] lg:w-[260px] p-4 md:p-6 sticky top-16 self-start'>
              <LeftSidebar currentLoginUserData={currentLoginUserData} />
            </aside>
            <main className='flex-1 overflow-y-auto p-4 md:p-6 pb-16 md:pb-6'>
              {children}
            </main>
          </div>
          <FloatingActionButtons />
          <BottomNavbar />
          <Toaster />
        </body>
      </html>
    </ClerkProvider>
  );
}
